# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = yes
RGBLIGHT_SUPPORTED = yes
SERIAL_DRIVER = vendor
VIA_ENABLE = yes
MIDI_ENABLE = yes
LED_MATRIX_DRIVER = is31FL3218
BACKLIGHT_ENABLE = yes